// Generated by scripts/release/generate-icon.sh from AppIcon.svg. Do not edit.
enum MenuBarCameraArtwork {
    static let pointWidth = 24
    static let pointHeight = 18
    static let pngBase64 = """
        iVBORw0KGgoAAAANSUhEUgAAADAAAAAkCAQAAABlTHGBAAAC4klEQVRIx+3Vz4uVVRzH8dfz3Bnn
        mk7OZEgjIzNFCwtiJlAkozBrryC1KE0JqWVQgWAujBYGiQVWiyiqhRXUlNDkP2ARlLmIDEUYBkFj
        yKYfd2bu9ebcp8W94/3xPOdpZmgVfc7m8D3f73mf8z3nfA//ZcX2+8mMskqwlc36XH94kigH8Lg3
        9amZUg36dBtQ8ojvQg5dwdCtXtGHMS+qBBaSWO09o3rCqwwBhh2zAVUfuhjcZ6Lo9/w81wEHfeZ8
        i7XfUVsa4896MieRKz0oykt0fajiB2+YM+u0GdzngELDo5B7TswrO+RCPmDWTRKcccyQooKC5B8m
        btW0MZN5DrMSiXkvOStZVjsamjpu6V9TNrjoVbdrILTf1lsUiZeQliwV3OZW/faJRM56fQEQYVrJ
        nJKiZMkTdyl7yv16jbrkpL1gcxNQ9aUjZpRdyXs0QUUmPGM3uCpRE6OvmaJ9vvYL7nZQ37J2MKbW
        6Deji03AyYapx7A1NxzyQJ1ntc5fKZ/uJqCphXV85S0V85mQWKzXc0Yy4tr9hGvRxz5StNXaDkgs
        ct6PuLMNkKUkD1AVO2St1Xa1HHvkkk/scsJ4Rko6dT0PkBgy7GldNtrUYn/fYds8ajwVkX5B1TxA
        5E+xLbqtb7OP2GiTqYyIKZO6rVdYyL6ZPAC/etsT1pkw0WLtd9iE4xn+R7xmlRG3KLssEjuTB9js
        lHNetqLtiOsVds51Q0Y7IqbBRfT6BpE/8gB7PZzzE1NMlcXoxlJKSk1zO+Ca+UZvhTv8K2oHTPrU
        joDnKjcvB9B5uYpud5eVKb+amu32ZIzUdcKe7NLSeQYVRa/W62CbElM+8ILnA6lbQoHcrhL4Fqve
        sdMXqqmRmgOLTRHbnAomgtOO6zHQ9tVyxbjfsgPS1/RnV20IAh5wj+87XnLk29D0WTuI7fSYNam8
        Fg0brNf4lPZ7d/EAKGTsrMugh+xwr96OqAt2O+d/LVd/A7rS6p5qMhgRAAAAAElFTkSuQmCC

        """
}
